#!/bin/bash

# Render Deployment Script for production environment
# Generated by deployment helper

echo "🚀 Starting Render deployment for production environment..."

# Deployment order is important:
# 1. Deploy workers first
# 2. Deploy primary server last (with worker URLs)

echo "📋 Deployment Order:"
echo "1. Upload workers"
echo "2. Chat workers" 
echo "3. General workers"
echo "4. Primary server (update worker URLs first)"
echo ""

echo "⚠️  IMPORTANT:"
echo "After deploying workers, update the primary server environment variables:"
echo "WORKER_SERVERS=https://forum-worker-production.onrender.com"
echo "UPLOAD_WORKERS=https://forum-upload-production.onrender.com"  
echo "CHAT_WORKERS=https://forum-chat-production.onrender.com"
echo ""

echo "📊 Monitoring endpoints after deployment:"
echo "Health: https://forum-primary-production.onrender.com/api/health"
echo "Status: https://forum-primary-production.onrender.com/api/cluster/status"
echo "Metrics: https://forum-primary-production.onrender.com/api/cluster/metrics"
echo ""

echo "✅ Deployment configurations generated in render-configs/ directory"
echo "Upload each YAML file to Render for the respective service"
